Repository FRONTENDBOOTCAMP-13th/JS-12-diary-4view, pull requests merged in 2025-05, with the labels that each got.

#27 ✨ feat: 일기 작성 페이지 제작
  src/pages/diary.html
  src/pages/diary.ts
Labels: enhancement

#30 ✨ feat: gpt 기능 구현
  src/chatbot-test.html
  src/utils/chatbot.ts
Labels: enhancement

#35 ✨ feat: Quoatable API를 이용한 명언 추천 기능 구현
  src/pages/diary.html
  src/utils/quotable.ts
Labels: enhancement

#37 ✨ feat: 일기 요약 기능 구현
  src/pages/diary.html
  src/utils/summary.ts
Labels: enhancement

#40 ✨ feat: 감정분석 기능 구현
  src/chatbot-test.html
  src/pages/result-emotion.html
  src/utils/emotion.ts
Labels: enhancement

#43 ✨ feat: Quotable API 문제로 JSON 기반 로직으로 전환 & Tenor API 이용 및 gif 추천 기능 구현
  public/JSON/quotes.json
  public/JSON/tags.json
  src/components/aisummary_quote.html
  src/utils/quotable.ts
  src/utils/tenor.ts
Labels: enhancement

#47 🐛 fix: GPT가 tags.json에 없는 태그를 반환하는 문제 해결
  src/utils/quotable.ts
Labels: bug

#61 Netlify Build 에러 해결
  src/pages/components/MusicCard/SpotifySearch.ts
  src/pages/components/MusicCard/index.ts
  src/pages/components/MusicCard/init.ts
  src/utils/openai.ts
Labels: bug

#65 quotable api, tenor api 관련 버그 수정
  src/utils/quotable.ts
  src/utils/tenor.ts
Labels: bug

#68 UserInfo 설정 단계 버그 및 기능 수정
  src/pages/userInfo/job.html
  src/pages/userInfo/preference.html
  src/pages/userInfo/profile.html
  src/pages/userInfo/profile.ts
Labels: bug, enhancement

#72 🐛 fix: 일기 내용이 로컬 스토리지에 없을 때, result.html에 접근 가능한 오류 해결
  src/pages/result.ts
Labels: bug
